### ISSUE TITLE
Fix Ussr/RUS for 1991

### ISSUE THREAD

**Issue by mayeulk** [unhcr/dataviz-population-change#11]
Currently the json creates a polygon with a hole for the Baltic countries in 1991. In fact two polygons are stacked, one being incomplete.
See screenshots:
![borders_ussr_russia_3](https://user-images.githubusercontent.com/768570/29131364-f57e27f4-7d2c-11e7-917a-1aa8144e2144.png)
![borders_ussr_russia_4](https://user-images.githubusercontent.com/768570/29131377-f88f7010-7d2c-11e7-9585-d9fec265f715.png)

This should be as follows (taken from my peaceprism repository):
![borders_ussr_russia_1](https://user-images.githubusercontent.com/768570/29131392-0739633c-7d2d-11e7-9482-e1b1e7f8a508.png)
![borders_ussr_russia_2](https://user-images.githubusercontent.com/768570/29131397-0af1eeae-7d2d-11e7-87f9-4ee31bcee6c2.png)

This issue would be fixed by using the file in this commit:
https://github.com/mayeulk/dataviz/commit/9159f20d86bcb2b034e5f1bdaeb60cb5ab61958c

**Comment by curran** [comment]
This issue can be closed, the implementation was merged in https://github.com/unhcr/dataviz/pull/12
