### ISSUE TITLE
 Swap increased and decreased icons

### ISSUE THREAD

**Issue by curran** [unhcr/dataviz-population-change#49]
Perhaps icons for increased and decreased should be swapped.

![image](https://user-images.githubusercontent.com/68416/30382409-a4d2622e-98bc-11e7-9730-596d6912ec79.png)

**Comment by vidonne** [comment]
<img width="59" alt="unhcr_historical_refugee_data" src="https://user-images.githubusercontent.com/1830612/30383434-f403a2b0-98a1-11e7-9943-93b9216f6fb3.png">
Icons have changed but not really center and appear multiple time

**Comment by curran** [comment]
Oh interesting! I did not realize. So it's more of a centering/positioning issue. The icons look good, just don't always display correctly.
