### ISSUE TITLE
Robinson map projection

### ISSUE THREAD

**Issue by LuisSevillano** [unhcr/dataviz-population-change#56]
Would you preffer to use the Robinson map projection instead the Equirectangular one? 
![rbonson_projection_on_dataviz-population-change](https://user-images.githubusercontent.com/11034169/30507755-0c79f266-9a89-11e7-8da9-3ed5cb78074d.png)

It would involve loading the packages `d3-geo` and `d3-geo-projection`.
Best regards!

**Comment by matthewsmawfield** [comment]
Hi Luis, thanks for the suggestions and contributions! I think that's a great idea.
